### ISSUE TITLE
warning message when removing adi from path

### ISSUE THREAD

**Issue by tatarbrot** [JimHokanson/adinstruments_sdk_matlab#10]
Hi 

I always get this error message: 

```
Warning: The following error was caught while executing 'adi.file_handle' class destructor:
Method 'delete' is not defined for class 'adi.file_handle' or is removed from MATLAB's search path. 
```

when I do this: 

```
function [data] = load_file(datafile)
addpath('adi');
data = adi.readFile(datafile);
...
rmpath('adi');
```

Is there a way to clean up before removing the path in order to avoid the error message? 

best
Tobias

**Comment by JimHokanson** [comment]
You could delete the object yourself before removing the path:

`delete(data);`

Is that what you are looking for? I'm not sure why you are changing the path ...

**Comment by tatarbrot** [comment]
Unfortunately this doesn't solve the problem (in my case). I just try to keep the path clean. 
Its not so important. I was just wondering if you'd know how to fix the problem :).

**Comment by JimHokanson** [comment]
Calling delete yourself before rmpath doesn't work?

I'm really curious as to why you try and keep the path clean. I will edit the path if I'm working on a particular project, but within a project I never bother removing paths. For what it is worth, I find it very helpful to use packages (as I did for this code) to reduce cluttering the function namespace.

One alternative that doesn't fit my use case, but that is possible, is to create a method that returns the entire file as a structure. This would allow closing all relevant handles. However, it is also potentially very memory intensive.

**Comment by tatarbrot** [comment]
I think I fixed the problem with a small hack: I removed the property state hidden for file_h in file.m and then deleting the corresponding obj.file_h before rmpath() works without a warning message.

**Comment by JimHokanson** [comment]
Oops, yeah I didn't realize that I hadn't tied deletion of the file object into the underlying c-interface handle (file_h). So yeah, my suggestion should be have been just to call:

` delete(data.file_h)`

You don't need to change the Hidden status of the property. Hidden still allows access, it is just meant to indicate that you shouldn't normally need to interface with that property, and hides the property from being displayed or from tab-completion.
