### ISSUE TITLE
Problem with mex file on linux

### ISSUE THREAD

**Issue by broggini** [JimHokanson/adinstruments_sdk_matlab#13]
Hi Jim,
If I try to run the sdk on linux I run into this error:
Sensorprams=adi.readFile(sensordata_path)
Unrecognized function or variable 'sdk_mex'.

Error in adi/sdk/openFile (line 156)
                    [result_code,pointer_value] = sdk_mex(0,h__toWChar(file_path));

Error in adi/readFile (line 68)
file_h   = sdk.openFile(file_path);

I think there is an issue with mex on linux.
Any Idea how to fix this?

Best regards,
Thomas

**Comment by JimHokanson** [comment]
The code I'm using relies on Windows binaries provided by ADInstruments and thus a Linux version is not available. If ADInsruments releases Linux support I'm happy to compile against it.

**Comment by JimHokanson** [comment]
Link to Python version issue:
https://github.com/JimHokanson/adinstruments_sdk_python/issues/3

**Comment by broggini** [comment]
Understood and very sad. thank you
