### ISSUE TITLE
Warnings because of sequence of chars %#

### ISSUE THREAD

**Issue by ftadel** [JimHokanson/adinstruments_sdk_matlab#14]
On Matlab 2020b, loading the class generates some warnings:
```
Warning: File: file.m Line: 25 Column: 20
Unrecognized pragma "%# of channels in the file (across all records). This may". 
Warning: File: file.m Line: 150 Column: 13
Unrecognized pragma "%# of comments". 
Warning: File: record.m Line: 13 Column: 19
Unrecognized pragma "%# of samples of highest sampling rate channel". 
```

You could just add a space between to two characters ("% #" to avoid the Matlab parser trying to interpret it.

**Comment by JimHokanson** [comment]
lol, awesome. I'll work on making that change. Thanks for the heads up.

**Comment by JimHokanson** [comment]
Finally closing this issue :/  Thanks again for pointing out this issue.
