### ISSUE TITLE
Nothing returned

### ISSUE THREAD

**Issue by DaveCumin** [JimHokanson/adinstruments_sdk_matlab#16]
UsingMATLAB R2020b on 64bit Windows 10 Enterprise.
Set up the sdk with ''addpath("...XXX....\adinstruments_sdk_matlab");', then tried to run 'f = adi.readFile("testData.adicht")' and there was no error, but there was also no 'f' object created. What could be going wrong?

**Comment by DaveCumin** [comment]
Thank you!

**Comment by JimHokanson** [comment]
Note to self, the `readFile` function now supports passing in a string as well.
