### ISSUE TITLE
Problem to add path in Matlab on Linux

### ISSUE THREAD

**Issue by dannyqchen** [JimHokanson/adinstruments_sdk_matlab#8]
Hello, 

This is a cool toolbox. I am trying to use it in Matlab on Linux, but it seems I cannot add '.../adinstruments_sdk_matlab/+adi/' into pathes. Should I remove '+'? 

Many thanks!

**Comment by JimHokanson** [comment]
Only add the adinstruments_sdk_matlab folder to the path. The '+' indicates a Matlab package, and you only add the parent folder of the package to the path, not the package itself.

**Comment by dannyqchen** [comment]
Many thanks, Jim!! 

 

I added the adinstruments_sdk_matlab, but I have problem to read my data. The error is:

 

Undefined function ‘sdk_mex’ for input  arguments of type ‘int16’. 

 

Error in adi/sdk/openFile (line 156)

 



 

 

Is that because of my data is int16? 

 

Thanks again!

**Comment by JimHokanson** [comment]
I would need to know what your code looks like to help out further

**Comment by dannyqchen** [comment]
Hi Jim,

 

My code is quite simple. Attached please find my example data. Please help me to check if I use your functions correctly. Many thanks!! 

 

----------------------------------------

addpath('/home/danny.chen/Programs/Matlab/LabChart/adinstruments_sdk_matlab-master/')

 

f_adi = {'Choice_1.adicht'};

f = adi.readFile(f_adi{1});

 

%  Undefined function 'sdk_mex' for input arguments of type 'int16'.

%  

%  Error in adi/sdk/openFile (line 156)

%                      [result_code,pointer_value] = sdk_mex(0,h__toWChar(file_path));

%  

%  Error in adi/readFile (line 68)

%  file_h   = sdk.openFile(file_path);

 

adi.convert(f_adi,'format','mat');

 

%  

%  Undefined function 'sdk_mex' for input arguments of type 'int16'.

%  

%  Error in adi/sdk/openFile (line 156)

%                      [result_code,pointer_value] = sdk_mex(0,h__toWChar(file_path));

%  

%  Error in adi/readFile (line 68)

%  file_h   = sdk.openFile(file_path);

%  

%  Error in adi/convert (line 101)

%      file_obj = adi.readFile(cur_file_path);

%  

 

--------------------------------------------------------

**Comment by JimHokanson** [comment]
Doh, I just reread your original post. My apologies, currently the underlying code from ADInstruments relies on Windows calls. The error you are getting is that I haven't compiled a wrapper for Linux, since I literally can't.

**Comment by dannyqchen** [comment]
Oh, I see. This makes sense. I’ll find Windows Matlab first. Many thanks!!

**Comment by dannyqchen** [comment]
Dear Jim, 

 

I ran your script in Windows Matlab. There is no problem to read the .adicht data now, but I got some errors to convert it to .mat file. Can you help me more on this? 

 

Many thanks!

**Comment by JimHokanson** [comment]
You can always post an issue. You don't need to ask for permission. Please start a different issue and post specifics as to what is not working. I haven't used the conversion code in a while so it is possible it has a bug or two.

**Comment by dannyqchen** [comment]
Dear Jim, 

I ran your script in Windows Matlab. There is no problem to read the .adicht data now, but I got some errors to convert it to .mat file. Can you help me more on this?  Many thanks! 


>> f_adicht = {'C:\\A_Temp\\Choice_1.adicht'};
>> f = adi.readFile(f_adicht{1});
>> adi.convert(f_adicht, 'save_path', 'C:\\A_Temp\\Choice_1.mat')
Undefined function 'exportToMatFile' for input arguments of type 'matlab.io.MatFile'.

Error in adi/record/exportToMatFile (line 104)
           exportToMatFile([objs.comments],m,conversion_options)

Error in adi/file/exportToMatFile (line 246)
            obj.records.exportToMatFile(m,conversion_options);

Error in adi/convert (line 112)
            save_path = file_obj.exportToMatFile(save_path,in.conversion_options);

**Comment by JimHokanson** [comment]
There was a bug when no comments were present in any record. Please update your code and try again.

**Comment by dannyqchen** [comment]
I tried to add comment, but I cannot edit file:


>> f = adi.editFile(f_adicht);
Warning: The following error was caught while executing 'adi.data_writer_handle' class destructor:
ADINSTRUMENTS:SDK:sdk:closeWriter  Unspecified error. 
> In adi/editFile (line 8) 
Error using adi/file_writer (line 155)
Not yet implemented

Error in adi/editFile (line 16)
file_writer = adi.file_writer(file_path, file_h, data_writer_h, false);

**Comment by JimHokanson** [comment]
The writing code doesn't work yet. You just need to update the code and
then having no comments should be fine.

**Comment by dannyqchen** [comment]
I am a little confused. I didn't add any comments in the data. Do you mean I need to empty some fields in f?

**Comment by dannyqchen** [comment]
I have just two lines of code here:

f_adicht = 'C:\\A_Temp\\Choice_1.adicht';
adi.convert(f_adicht, 'save_path', 'C:\\A_Temp\\Choice_1.mat')

**Comment by JimHokanson** [comment]
I have modified my code and posted a new version on Github. You need to
download that code, which contains a bug fix. Then your code should work.

**Comment by dannyqchen** [comment]
It works very well now. Thank you very much!
